schema_version: 1

context:
  version: "0.16.0"

package:
  name: hypothesis-awkward
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/h/hypothesis-awkward/hypothesis_awkward-${{ version }}.tar.gz
  sha256: b7780f71957675f5bf4f1e211614a4ed711a3b38133d8d2c081e77b9f2fd7004

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-regex-commit
  run:
    - python >=${{ python_min }}
    - awkward >=2.9
    - hypothesis >=6.147
    - typing_extensions >=4.1

tests:
  - python:
      imports:
        - hypothesis_awkward
        - hypothesis_awkward.strategies
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Hypothesis strategies for Awkward Array
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/scikit-hep/hypothesis-awkward
  repository: https://github.com/scikit-hep/hypothesis-awkward
  documentation: https://scikit-hep.github.io/hypothesis-awkward/

extra:
  recipe-maintainers:
    - TaiSakuma
